all: dine1 dine2 dine3 dine4

dine1: dinea_1.c
			gcc -o dine1 dinea_1.c
dine2: dinea_2.c
			gcc -o dine2 dinea_2.c
dine3: dineb_1.c
			gcc -o dine3 dineb_1.c
dine4: dineb_2.c
			gcc -o dine4 dineb_2.c