all: fifo1 fifo2 share1 share2

fifo1: fifo_1.c
			gcc -o fifo1 fifo_1.c
fifo2: fifo_2.c
			gcc -o fifo2 fifo_2.c
share1: shared_1.c
			gcc -o share1 shared_1.c
share2: shared_2.c
			gcc -o share2 shared_2.c
